# Generated by Django 5.1.4 on 2025-01-06 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authtoken', '0004_alter_tokenproxy_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
