# Generated by Django 5.1.4 on 2025-01-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='splite_type',
            new_name='split_type',
        ),
    ]
