# Generated by Django 5.1.4 on 2025-01-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group_type', models.CharField(choices=[('hostel_roommates', 'Hostel Roommates'), ('project_teams', 'Project Teams'), ('trip_groups', 'Trip Groups')], max_length=30)),
                ('members', models.ManyToManyField(to='account.student')),
            ],
        ),
    ]
