# Generated by Django 5.1.4 on 2025-01-04 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], max_length=20)),
                ('settlement', models.CharField(choices=[('upi', 'UPI'), ('cash', 'Cash'), ('bank', 'Bank')], max_length=20)),
                ('due_date', models.DateField()),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_recived', to='account.student')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_made', to='account.student')),
            ],
        ),
    ]
